name: 'course_advanced_dbt'
version: '1.0.0'
config-version: 2

profile: 'course_advanced_dbt'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

log-path: 'logs'
target-path: 'target'
packages-install-path: 'dbt_packages'

clean-targets:
  - "target"
  - "dbt_packages"

models:
  course_advanced_dbt:
    +materialized: view
    +grants:
      select: ['transformer', 'reporter']

    staging:
      +schema: staging

    intermediate:
      +schema: intermediate

    marts:
      core:
        +schema: core_reporting
        +docs:
          node_color: "purple"
      finance:
        +schema: finance
      product:
        +schema: product

  # hide dbt_project_evaluator package output from docs.
  dbt_project_evaluator:
    +docs:
      show: false

seeds:
  dbt_project_evaluator:
    dbt_project_evaluator_exceptions:
      +enabled: false
  unit_testing:
    +schema: unit_testing
    +tags: unit_testing
    expected_output_rolling_test_data:
      +column_types:
        CREATED_AT: DATE
        FRUIT: VARCHAR
        PRICE: FLOAT
        AVG_3_PERIODS_PRICE: FLOAT
        AVG_7_PERIODS_PRICE: FLOAT
        AVG_14_PERIODS_PRICE: FLOAT
on-run-end: "{{ dbt_project_evaluator.print_dbt_project_evaluator_issues() }}"
